site_name: Pymaker - Easily generate a new Python Project
site_url: https://pymaker.seapagan.net/

theme:
  name: material
  palette:
    primary: light-blue
    accent: blue
  features:
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - toc.follow
extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pyproject-maker/
    - icon: fontawesome/brands/github
      link: https://github.com/seapagan/py-maker
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gnramsay_dev
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: © 2023-2024 Grant Ramsay (Seapagan)

hooks:
  - docs/hooks/google_style_notes.py

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocstrings
  - latest-git-tag
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true

repo_url: https://github.com/seapagan/py-maker
repo_name: seapagan/py-maker

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: false
      auto_title: false
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Configuration: configuration.md
  - Templates:
      - Internal Template: template/internal.md
      - Modifying: template/modify.md
      - Replacing: template/replace.md
  - Task Runner: tasks.md
  - Future Plans: future-plans.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - License: license.md
